# Generated by Django 5.1.1 on 2024-09-22 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'permissions': [('edit_car', 'Can edit car')]},
        ),
    ]
