# Generated by Django 5.1.1 on 2024-09-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table=None,
        ),
    ]
